language: java

branches:
  only:
    - master

sudo: false

before_install:
  - rm -rf ~/.linuxbrew
  - yes | ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/linuxbrew/go/install)"
  - export PATH="$HOME/.linuxbrew/bin:$PATH"
  - export MANPATH="$HOME/.linuxbrew/share/man:$MANPATH"
  - export INFOPATH="$HOME/.linuxbrew/share/info:$INFOPATH"
  - cd $(brew --prefix) && git fetch && git reset --hard origin/master
  - brew install jdk
  - cd ~
  - git clone https://github.com/kframework/k/
  - cd k
  - mvn package -DskipTests
  - export PATH=$PATH:$(realpath k-distribution/target/release/k/bin)

install:
  - make

script:
  - cd test
  - ktest config.xml
