language: java

dist: trusty

branches:
  only:
    - master

sudo: false

before_install:
  - cd $HOME
  - git clone https://github.com/kframework/k/
  - cd k
  - mvn package -DskipTests
  - export PATH=$PATH:$(pwd)/k-distribution/target/release/k/bin
  - cd project

cache:
  directories:
    - $HOME/k


install:
  - make

script:
  - cd test
  - ktest config.xml

notifications:
  email:
    - tosun2@illinois.edu
