language: java

dist: trusty

branches:
  only:
    - master

sudo: false

before_install:
  - cd ~
  - git clone https://github.com/kframework/k/
  - cd k
  - mvn package -DskipTests
  - export PATH=$PATH:$(realpath k-distribution/target/release/k/bin)

install:
  - make

script:
  - cd test
  - ktest config.xml
